kind: pipeline
name: checks

steps:
  - name: restore
    image: homerovalle/drone-gcs-cache
    settings:
      json_key:
        from_secret: gcs_cache_json_key
      restore: true
      path: hawk-ci/regnum-ci/cache
  - name: compile
    image: openjdk:12-jdk-oraclelinux7
    commands:
        - ./gradlew -Dorg.gradle.daemon=false compileJava compileKotlin
  - name: dokka
    image: openjdk:12-jdk-oraclelinux7
    commands:
      - ./gradlew -Dorg.gradle.daemon=false dokka
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
  - name: publish
    image: plugins/gh-pages
    settings:
      username: SchlaubiBot
      password:
        from_secret: github_password
      pages_directory: public/
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
  - name: rebuild
    image: plugins/s3-cache
    image: homerovalle/drone-gcs-cache
    settings:
      bucket: hawk-ci
      json_key:
        from_secret: gcs_cache_json_key
      rebuild: true
      path: hawk-ci/regnum-ci/cache
      mount:
        - .gradle/
